baseurl = "http://samnnodim.com"
title = "Samuel O Nnodim"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  # description = "So Fresh & So Clean"
  description = "Web Designer, Developer and Guru"
  logo = "fa-diamond"
  copyright = "Obi Knows Inc"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://twitter.com/obiiiknows"

# [[params.social]]
#   medium = "instagram"
#   icon = "instagram"
#   link = "#"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/obiknows"

[languages]
[languages.en]
languageName = "English"
weight = 1

